#!/bin/bash -u
. ./cmd.sh
. ./path.sh

mic=rcnn_tri0
expdir=exp_cntk/$mic
datadir=data-fbank
alidir=/home/zhaoyue/kaldi/egs/timit/s5/exp/tri3_ali

labelDim=1954  #number of output units, you have to check your gmm setup to get this number
# featDim=40x3x11=1320
featDim=1320
stage=0

cn_gpu=/home/zhaoyue/CNTK/build/release/bin/cntk

feats_tr="scp:$datadir/train_tr90/feats.scp"
feats_cv="scp:$datadir/train_cv10/feats.scp"
labels_tr="ark:ali-to-pdf $alidir/final.mdl \"ark:gunzip -c $alidir/ali.*.gz |\" ark:- | ali-to-post ark:- ark:- |"
labels_cv="ark:ali-to-pdf $alidir/final.mdl \"ark:gunzip -c $alidir_cv/ali.*.gz |\" ark:- | ali-to-post ark:- ark:- |"
  
mkdir -p $expdir

if [ $stage -le 0 ] ; then
(feat-to-len "$feats_tr" ark,t:- > $expdir/cntk_train.counts) || exit 1;
echo "$feats_tr" > $expdir/cntk_train.feats
echo "$labels_tr" > $expdir/cntk_train.labels

(feat-to-len "$feats_cv" ark,t:- > $expdir/cntk_valid.counts) || exit 1;
echo "$feats_cv" > $expdir/cntk_valid.feats
echo "$labels_tr" > $expdir/cntk_valid.labels

for (( c=0; c<labelDim; c++)) ; do
  echo $c
done >$expdir/cntk_label.mapping

fi


if [ $stage -le 1 ] ; then

### setup the configuration files for training CNTK models ###
cp cntk_config/rcnn_tri0.cntk $expdir/rcnn_tri0.cntk
cp cntk_config/default_macros.ndl $expdir/default_macros.ndl
cp cntk_config/rcnn_tri0.ndl $expdir/rcnn_tri0.ndl
ndlfile=$expdir/rcnn_tri0.ndl

tee $expdir/Base.config <<EOF
ExpDir=$expdir
logFile=train_cntk
modelName=cntk.rcnn_tri0

labelDim=${labelDim}
featDim=${featDim}
labelMapping=${expdir}/cntk_label.mapping
featureTransform=NO_FEATURE_TRANSFORM

inputCounts=${expdir}/cntk_train.counts
inputFeats=${expdir}/cntk_train.feats
inputLabels=${expdir}/cntk_train.labels

cvInputCounts=${expdir}/cntk_valid.counts
cvInputFeats=${expdir}/cntk_valid.feats
cvInputLabels=${expdir}/cntk_valid.labels
EOF

## training command ##
$cn_gpu configFile=${expdir}/Base.config configFile=${expdir}/rcnn_tri0.cntk DeviceNumber=1 action=Train ndlfile=$ndlfile

echo "$0 successfuly finished.."

fi
# display result
grep EvalErrPerSample $expdir/log/train_cntk_Train.log


#decode part
# graphdir should not be chosen randomly
# graphdir should contain HCLG.fst, generated by utils/mkgraph.sh in data preprocessing
graphdir=/home/zhaoyue/kaldi/egs/timit/s5/exp/tri3/graph
config_write=cntk_config/cntk_write.cntk
cnmodel=$expdir/cntk.rcnn_tri0
action=write
# decode_cntk2.sh require final.mdl in $expdir
cp $alidir/final.mdl $expdir

cntk_string="$cn_gpu configFile=$config_write DeviceNumber=1 modelName=$cnmodel labelDim=$labelDim featDim=$featDim action=$action ExpDir=$expdir"
scripts/decode_cntk2.sh  --nj 1 --cmd run.pl  --acwt 0.2 $graphdir $datadir/test $expdir/decode_timit_test "$cntk_string" || exit 1;
scripts/decode_cntk2.sh  --nj 1 --cmd run.pl  --acwt 0.2 $graphdir $datadir/dev $expdir/decode_timit_dev "$cntk_string" || exit 1;

echo " "
for x in $expdir/decode*; do [ -d $x ] && echo $x | grep "${1:-.*}" >/dev/null && grep Sum $x/score_*/*.sys 2>/dev/null | utils/best_wer.sh; done

sleep 3
exit 0

